flake.nix
This fixes some weirdness we encountered with the recent upgrade of `pnpm` to `8.5.1`, where `npx` tried to install `7.x` and then the Nix shell bootstrap step failed.
=> fix: specify the version of `pnpm` to install with `npx`

flake.nix, package.json, pnpm-lock.yaml
Installing `pnpm` via `npx`, a dev dependency in `package.json`, and a
bootstrap step worked pretty well until our most recent upgrade (to
`pnpm` 8.5.1). Now we're running into a number of strange issues.
Let's just install `pnpm` from Nix. Contributors who aren't using Nix
can install a compatible `pnpm` version using whatever non-Nix
mechanism they prefer.
Note to current contributors: you will probably have to `rm -rf
node_modules` and then re-enter the Nix shell.
=> chore: install `pnpm` from `nixpkgs`

.prettierignore
=> chore: tell `prettier` to ignore all `*.md` files

src/components/TreeReactFlow/index.tsx
Prior to this change, panning could be quite frustrating, because if the cursor was placed over a node or an edge of a `ReactFlow`, the flow didn't propagate the pan/drag event to the underlying canvas. Now it works everywhere on the canvas, regardless of what's underneath the cursor.
=> feat: pan the canvas regardless of what's underneath the pointer

src/Actions.tsx, src/components/ActionButton/index.tsx, src/components/ActionPanel/index.tsx, src/components/ActionPanelButton/ActionPanelButton.stories.tsx, src/components/ActionPanelButton/index.tsx, src/components/index.ts
Among the changes here are:
* All buttons in the action panel now have consistent styling
* Buttons without either a description or a "name" (i.e., short label) are short, buttons with both are tall.
* Format offered variables (names) as code
* When only a name appears on a button, center it. This means the list of offered variables will now be centered, rather than right-ragged.
=> chore: factor out a generic action panel button type

package.json, pnpm-lock.yaml, src/Types.ts, src/components/Avatar/Avatar.stories.tsx, src/components/Avatar/index.tsx, src/components/examples/accounts.ts
The packages we were using are no longer maintained. The replacement
packages have a slightly different API, and have dropped support for
the `jdenticon` style, unfortunately. We could add this back by using
the `jdenticon` package directly, but it would complicate the `Avatar`
type and isn't worth the time investment, for now.
=> chore: replace deprecated Dicebear avatar packages

orval.config.ts
Maybe we'll pay more attention to these at a later date, but for now they're just an annoyance.
=> chore: disable IBM OpenAPI validator warnings

package.json, pnpm-lock.yaml, src/App.tsx, src/ChooseSession.tsx, src/Edit.tsx, src/Types.ts, src/components/Avatar/index.tsx, src/components/SessionsNavBar/index.tsx, src/components/examples/accounts.ts, src/main.tsx
We use this cookie in lieu of a proper account system. No personally identifiable information is stored: it's just a random v4 UUID that gets set when the page is loaded, and expires after 2 days. In the app, we only use this to set the avatar image to something unique. In production deployments, this abstract cookie should also help us with load balancing, as we should be able to use it to pin the visitor to a particular instance.
=> feat: set an `id` cookie

src/Edit.tsx, src/components/TreeReactFlow/TreeReactFlow.stories.tsx, src/components/TreeReactFlow/index.tsx
This mirrors the earlier scroll-to-definition feature.
=> feat: scroll to typedef when its name is clicked

src/components/ActionPanelButton/ActionPanelButton.stories.tsx, src/components/ActionPanelButton/index.tsx, src/components/Sidebar/Sidebar.stories.tsx, src/components/Sidebar/index.tsx, src/components/TreeReactFlow/TreeReactFlow.stories.tsx, src/components/TreeReactFlow/index.tsx, src/components/examples/trees.ts
This fixes what is, IMO, our most egregious visual UI issue, which is that long names (variables, definitions, etc.) aren't clipped to fit their container boundaries. In some cases, such as action panel buttons, this is a minor annoyance, but in the case of React Flow trees, it's absolutely awful.
I believe this PR covers all cases where names can appear. It also adds tooltip support for React Flow nodes, where names are more likely to be clipped. The tooltips are also useful for cases where the tree has been zoomed out such that node labels are no longer legible.
=> fix: truncate names to fit their containers

package.json
This stems from trying to develop on my Arch-Linux-based personal laptop, without using Nix. Partly just out of curiosity, partly to see whether external contributors might be able to get away with not using Nix, and partly because using Nix has been more help than hindrance so far for the particular work I've wanted to do on that machine.
We will likely never reflect the full version ranges we _could_ use, across all dependencies, and Nix will remain the recommended way to build the app. But there's no harm in widening some bounds slightly when we know they work.
I considered also adding `"node": "*"` under the `"overrides"` section, which allows us to run `pnpm install`. But this isn't actually necessary for the more common `pnpm build` and `pnpm watch` steps, so I've left it out for …
=> chore: Allow building with Node 19 and 20

src/Edit.tsx, src/components/EvalFull/index.tsx, src/components/TreeReactFlow/index.tsx, src/util.ts
With this change, we can parent React components to `TreeReactFlow` and `TreeReactFlowOne`. Among other things, this removes a bunch of hacks we needed to asynchronously determine the size of the canvas when rendering the `PictureInPicture` and `Toolbar` components, which overlay it.
Now that we can parent one `TreeReactFlow` inside another, we need to add a `ReactFlowProvider` around each nested use of React Flow in order for them to coexist. This is the responsibility of the caller to get right, the advantage being that we can now get & use internal React Flow state from pretty much anywhere.
=> feat: add `children` support to `TreeReactFlow` and `TreeReactFlowOne`

src/components/EvalFull/index.tsx
This series of commits fixes the issue where the live eval results in the `PictureInPicture` window weren't nicely re-fitted whenever the definition selection changed, nor when the definition's value changed due to an edit.
=> fix: re-fit live eval results when they change

argocd/base/statefulset.yaml, flake.lock, flake.nix, src/Actions.tsx, src/primer-api/model/getActionOptionsAction.ts, src/primer-api/model/inputAction.ts, src/primer-api/model/noInputAction.ts
This bumps the Primer pin to
`026a3490d29d3ea7841d185930c3467bb3133831`, which supports new typedef
actions (type parameters & deletion in additional scenarios).
(Note that the backend implementation is a bit buggy, but this is a
known issue.)
=> feat: support new typedef actions

src/components/PictureInPicture/index.tsx
We put this on the right, rather than the conventional top. This is
for 2 reasons:
1. We're very vertically constrained already on typical 16:9 laptop
aspect ratios.
2. It leaves the door open for adding additional tools/controls,
toolbar-style.
=> feat: add a drag bar to the PIP

src/components/TreeReactFlow/index.tsx
This was a pretty stupid bug (introduced by me). One of the small things I'd like to tackle after the demo push is factoring out our ID creation, frontend and backend, with a rough proof of uniqueness.
=> fix: Ensure typedef param node IDs are unique

src/components/TreeReactFlow/index.tsx
In practice, this removes unexpected rings around all nodes in the type display and eval trees.
=> fix: Don't consider node's with undefined selection to be selected

.github/workflows/deploy-frontend-zurihac.yaml
Push to the `zurihac` branch to activate.
Note that Cloudflare Pages can only point alias domains to "production" branch deployments, so we'll need to find another way to update the zurihac.hackworth.codes domain when a new deployment is made to this branch.
=> ci: add a ZuriHac Pages deployment

argocd/base/statefulset.yaml, flake.lock, flake.nix
This brings this repo up-to-date with `primer` upstream `main`. There are no frontend-visible changes here.
=> chore: bump Primer pin

src/components/TreeReactFlow/index.tsx
Mainly we bring the border styling in line with other nodes and make the label font less loud. I think we already draw enough attention to these special nodes due to their size, but here we also use a slightly "electric" border color and also increase the font size and weight a bit vs. normal nodes.
We've also increased contrast by ditching the grey background. (We would like to move towards a grey canvas background, anyway, so the old background color would have clashed.)
One drawback to the new style is that definition names are harder to see when zoomed out, but we have other ways to locate definitions (e.g., clicking on their names in the sidebar), and we have tooltips on hover, as well. (One benefit to making the font size smaller is that definition names can be longer before they're …
=> style: restyle definition & typedef nodes

src/Edit.tsx
This should fix iPad issues with the edit page not quite fitting and scrolling off the bottom of the display.
Ref:
* https://github.com/tailwindlabs/tailwindcss/discussions/8216#discussioncomment-4621818
* https://web.dev/viewport-units/
=> style: use Tailwind directive to get 100dvh support

src/Edit.tsx
When I removed the sidebar in
e3428ec1811fc94336d8fa0f416f896c7b215cd1, I didn't consider what happens when there's no selection: we don't render the action panel, but that's where the "add new def" and "add new type" buttons are now!
We now render just those 2 actions in the action panel when there's no selection. This has the nice side effect of getting rid of the not very helpful and hastily designed message that we used to display when this happens.
Note that the "fixes" are more like hacky workarounds. The action panel wasn't designed to be shown without a selection, so we pass some console logging `on*` handlers to catch any problems that might arise due to this change. We should refactor things to properly support this scenario, though.
=> fix: show global actions when there is no selection

argocd/base/statefulset.yaml, flake.lock, flake.nix, src/Edit.tsx
We bump the Primer pin (still running off
https://github.com/hackworthltd/primer/pull/1070, FYI) and bump the eval step limit to 300.
=> chore: bump eval limit

src/components/TreeReactFlow/Flavor.ts, src/components/TreeReactFlow/index.tsx
This is a cleaned-up version of the bulk of #980/#987.
I've fixed up comments and commit messages, and rebased to fold last commit in earlier. I also fixed a bug where edges out of `THole` were invisible - this turned out to be due to a typo (`stroke-red-tertiaryy`).
=> Node styling improvements

src/components/TreeReactFlow/Flavor.ts, src/components/TreeReactFlow/index.tsx
I mistakenly merged without the fixes corresponding to this thread: https://github.com/hackworthltd/primer-app/pull/997#discussion_r1246737671.
=> Small fixes to #997

orval.config.ts, package.json, pnpm-lock.yaml
Our workaround is no longer necessary.
=> chore: use `OperationOptions` from `@orval/core`

package.json, pnpm-lock.yaml, src/App.tsx
Note that this package, and its floating activation button, are only active in development mode, but can also be loaded in production mode by typing `window.toggleDevtools()` in the JavaScript console.
Ref:
https://tanstack.com/query/v4/docs/react/devtools
=> chore: add `@tanstack/react-query-devtools`

src/Types.ts, src/components/ChooseSession/index.tsx, src/components/SessionList/SessionList.stories.tsx, src/components/SessionList/index.tsx, src/components/SessionPreview/SessionPreview.stories.tsx, src/components/SessionPreview/index.tsx, src/components/SessionsPage/SessionsPage.stories.tsx, src/components/SessionsPage/index.tsx, src/components/examples/sessions.ts, src/components/index.ts
This is the first in a series of cleanups of the `ChooseSession` and related components, which I plan to use as exemplars of how to make the frontend production-ready.
=> fix: invalidate session list upon successful session creation

.github/workflows/build-frontend.yaml, src/components/Edit/index.tsx, src/components/EvalFull/index.tsx, src/components/SelectionInfo/index.tsx, src/components/Toolbar/Toolbar.stories.tsx, src/components/Toolbar/index.tsx, src/components/TreeReactFlow/Flavor.ts, src/components/TreeReactFlow/TreeReactFlow.stories.tsx, src/components/TreeReactFlow/Types.ts, src/components/TreeReactFlow/index.tsx
At a recent in-person meeting, @dhess mentioned wanting to move labels to the left, and after thinking about it I said I'd like to try a bigger change, with labels brought down to the height of the main node contents. This is a mock-up of that change.
Pros:
- Reads nicely (more text-like) for `λ` and `∀` nodes.
- Allows us to make better use of space on the canvas, since the more uniform shape of nodes means we don't need to worry about labels overlapping with edges or other nodes.
- I personally just much prefer it on a base aesthetic level - it feels cleaner.
Still to do:
- Revisiting this a few weeks later, I'm not totally sure what I considered the problem to be. I guess it's that the label and contents blur together due to both having solid backgrounds? If so, I don't think it's a …
=> Bring node labels in-line

src/components/TreeReactFlow/index.tsx
See https://github.com/hackworthltd/primer-app/pull/1005#issuecomment-1663729341.
=> feat: Display node labels in top-left corner instead of top-right

flake.lock, flake.nix
We can now run `nix fmt` in the Nix shell and format all source files at once, regardless of the formatter needed, and quickly (once cached).
=> chore(nix): switch to `treefmt`

src/components/TreeReactFlow/Flavor.ts, src/components/TreeReactFlow/Types.ts, src/components/TreeReactFlow/index.tsx
This is sort of a follow-up to #1005, in terms of trying to make programs more text-mode-like and readable. @dhess mentioned this feature in https://github.com/hackworthltd/primer-app/pull/1005#issuecomment-1623383632, and I replied in https://github.com/hackworthltd/primer-app/pull/1005#issuecomment-1663895080 about how we really have two different sorts of labels. This PR hides those which are just "annotations".
If we don't like this change, I should separately merge the first few commits, as they are mostly clean-ups of #1005 and are generally a good thing regardless.
=> Add option to hide non-syntax labels in expert mode 

package.json, pnpm-lock.yaml, src/App.tsx, src/components/Edit/index.tsx, src/components/Toolbar/index.tsx, src/components/TreeReactFlow/Types.ts, src/components/TreeReactFlow/index.tsx
Discussions in #1005 and #1023 about how to toggle experimental features led me to finally look in to something I've long-thought we could do with: an area in the UI for developers only.
We had something similar in the bottom-right corner in Vonnegut, except that IIRC, while that was only intended for development use, it also appeared in the production build. And I can't remember quite what we actually used it for altogether (I think there was an option to dump a JSON serialisation of the current program?).
We already added a dev-only menu in #1002. But that was specifically for React Query. This PR essentially extends that with a bespoke menu for Primer-specific settings.
For convenience in avoiding potential conflicts, this is currently based on #1023.
Feel free to bikeshed. This is …
=> Add developer menu

src/components/TreeReactFlow/index.tsx
=> fix: Don't round corners of type-level labels

src/components/TreeReactFlow/Types.ts, src/components/TreeReactFlow/index.tsx, src/components/TreeReactFlow/layoutTree.ts
The last commit fixes something which would otherwise become a much bigger problem after #1036, since kinds can then be near non-kinds. Although I haven't yet tried combining the changes. It's possible that we would then want to add vertical padding alongside the existing horizontal padding. But this would be trivial to implement now.
=> fix: Add extra padding to kind and definition nodes

.github/workflows/build-frontend.yaml, .github/workflows/deploy-storybook.yaml
Tidy doesn't like later versions.
=> chore: use Nodejs 18.x for GitHub CI

argocd/base/statefulset.yaml, flake.lock, flake.nix, src/components/TreeReactFlow/Flavor.ts, src/components/examples/trees.ts, src/primer-api/model/edgeFlavor.ts, src/primer-api/model/nodeFlavorNoBody.ts, src/primer-api/model/nodeFlavorTextBody.ts
This PR corresponds to the backend PR https://github.com/hackworthltd/primer/pull/1183.
As noted in that backend PR, we cannot yet select the name nodes. We want to enable this, but it'll take some additional backend work. See https://github.com/hackworthltd/primer/issues/75 and https://github.com/hackworthltd/primer/issues/93.
=> feat: render separate binders and names

argocd/base/statefulset.yaml, flake.lock, flake.nix
No functional changes here, this only brings us up-to-date with the
latest build of the backend.
=> chore: bump Primer pin to latest `main`

flake.lock, flake.nix, src/components/TreeReactFlow/Types.ts
Also, replace `rnix-lsp` with `nil` as the former is no longer
maintained.
=> chore(nix): bump dependencies

src/components/TreeReactFlow/index.tsx, src/primer-api/primer-api.ts, tsconfig.base.json
This setting is causing problems for us with one package we'd like to use:
https://github.com/hackworthltd/primer-app/pull/1012#issuecomment-1633324926
and is also preventing us from migrating to TypeScript 5 due to an upstream issue in `react-router` that's been unaddressed for almost a year:
https://github.com/hackworthltd/primer-app/issues/898
There were no objections to disabling it, so we do so in this commit. (There is one minor code change required as a result, just an additional optional property check on a `onNodeClick` handler in our React Flow wrapper.)
Closes https://github.com/hackworthltd/primer-app/issues/898
=> chore(typescript): disable `exactOptionalPropertyTypes`

src/components/TreeReactFlow/Types.ts, src/components/TreeReactFlow/index.tsx
Behaviour is probably what we want, but implementation still a little messy.
We only display labels for `let` nodes for now. Eventually we might want to do more with this, including even labelling every single edge in beginner mode.
I had previously thought that labels should be on the outgoing connection rather than the edge itself, out of concern that the latter would look a bit like a node, and as an indication that the number of edges and their names is a property of the parent. But this design, with borderless labels, as iterated on with @dhess last week, actually looks alright.
Closes https://github.com/hackworthltd/primer-app/issues/24, I suppose.
=> feat: Add edge labels
